language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: oMHI2yYeVS1263URexHk2jhwY7oPaYt7IBDc7hhgb/83TBgDWasUV4MUNsMQxriCkk3dawx0We91Rksq7QkC2V5VLC2Ki17h+WoC6HkmTVPQ5dYaAM7BG3Lc0UYDKCP+ZahGOKJIf1gxYczigeD/dX0ZeJXGdODb3JOS31BZ+pxEC0SbTxEgpL7OPOIdWfou3jnrFRWTt4N5FOfSiJAuO2oZ3ZkkjfWF3+bijiL8V6xDAoP14QFtsG7tLmMY/1TasZ2bcMb8AgSWOY4pEWThNurndn+c33VzyinvvSsRFMYLpT3vpFKCxTSudsxBg5Gyl0iNWBodBvqFhiiN1SdGv7SZ3TQgly7DJDL5QMNmIcna7ItUkrNXilHhfsKyoYNEXEz9ir0H7dZPIDCF7ULQZE58r8bSdi9PP3P5aKjyKO5Mx9Ap4jNupyCVCt6p4PTua9pLo/slV86TsLZIYIHUrkFclK2krHJG2nwsdvgLS8h0+dfdp5lP1gXIvm9l5GYVPkbMHcKuPhmkpr8D5csYnIJrLhm8XUaRakacE/4gY4ovDf0r3K486+sPK5+1uE5Gvlgnu4O4OAEjeIG52XvccKd2MmnKNef5k3WX3d4KnpxyRQ3mJ5FnnJ7VpqnxR9matrvf9BFQ3p1o5rfwrSKSvUB4kopSSeSkZ1+WAcwkQcU=
  file:
    - "hast-util-embedded.js"
    - "hast-util-embedded.min.js"
  on:
    tags: true
    node: '9.0'
