language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: f50M9a6Fe1zSNyBk6mFl+S33Q6GI93COM9eUyWynco92SUaNDF4S7p3E7tsrm7E4lxdCPK8xNUW1JshPxnpvyb1vpXmsgcUn3njzzUfw4zFd7X5qnPT2IaCXpjBBykj/jTcKPRlOc3O4GvtInUa5td1CCyRR/ompYTDZJ7dsMB44d5iUMD/aBiumWcGWQ/3aNMbmOR50+5PAtFuGDmr3w/k5QzdYmUB47ddm4CfZ9EarGxSokITtyhizQNEwboQxOct2rloZIhQHS+FQFABXFhBLssuzJldWKSYxCfUGyvlxow8s7H+5Aer/MnK58SuPp3+VijaAWhjYxD3hBqPneox4K9yZT2IyQz2rj5Ogmu8/dQjSlcgg2iccYZ+qzVFwrZcRMktnxq87yib9hoGYX5ZgAtxjpNsaRV816BguqUqXPKM/gAaQyn2bMLWYpFugK2PzISFo1Mdrj8MHupPKOoyKBYd475RYB5h8A0bOslH3cVn1W8UNAnpCL7MoZWxgfjGWIQr4bwX+Mr8HZ8QGN3frJs6mbRS6EdoU9jJV7SgH5O0JhAvhJVZ4+KaQofXLDV/FmisFofCm/tTKTQ9iX5oJerqT9QdpZ8ekiPHdQbhtj8XmyDCkLHy735TOmf5YCJ7b4NWKPDPu3fJpc/00ip6amkMPjV2oAVYK/4948ys=
  file:
    - 'hast-util-embedded.js'
    - 'hast-util-embedded.min.js'
  on:
    tags: true
